Bugfix 8373:  Create kernel routes for IPv6 destination prefixes when the tunnel is up.
Details
Create route for the remote, protected subnet via the wan interface over which the ipsec-tunnel is created.

diff --git a/src/_updown/_updown.in b/src/_updown/_updown.in
--- a/src/_updown/_updown.in
+++ b/src/_updown/_updown.in
@@ -194,6 +194,17 @@ downroute() {
 	ip route flush cache
 }
 
+
+uproute_v6() {
+	doroute6 add
+	ip -6 route flush cache
+}
+
+downroute_v6() {
+	doroute6 delete
+	ip -6 route flush cache
+}
+
 addsource() {
 	st=0
 	if ! ip -o route get ${PLUTO_MY_SOURCEIP%/*} | grep -q ^local
@@ -208,6 +219,25 @@ addsource() {
 	    if test " $oops" != " " -o " $st" != " 0"
 	    then
 		echo "$0: addsource \`$it' failed ($oops)" >&2
+	    fi
+	fi
+	return $st
+}
+
+addsource6() {
+	st=0
+	if ! ip -6 -o route get ${PLUTO_MY_SOURCEIP%/*} | grep -q ^local
+	then
+	    it="ip -6 addr add ${PLUTO_MY_SOURCEIP%/*}/128 dev $PLUTO_INTERFACE"
+	    oops="`eval $it 2>&1`"
+	    st=$?
+	    if test " $oops" = " " -a " $st" != " 0"
+	    then
+		oops="silent error, exit status $st"
+	    fi
+	    if test " $oops" != " " -o " $st" != " 0"
+	    then
+		echo "$0: addsource6 \`$it' failed ($oops)" >&2
 	    fi
 	fi
 	return $st
@@ -288,6 +318,71 @@ doroute() {
 	fi
 	return $st
 }
+
+doroute6() {
+	st=0
+
+	if [ -z "$KLIPS" -a -z "$PLUTO_MY_SOURCEIP" ]
+	then
+	    # leave because no route entry is required
+	    return $st
+	fi
+
+	parms1="$PLUTO_PEER_CLIENT"
+	
+	parms2=
+	if [ -n "$PLUTO_NEXT_HOP" ] && [ "$PLUTO_NEXT_HOP" != "$PLUTO_PEER" ]
+	then
+	    parms2="via $PLUTO_NEXT_HOP"
+	fi
+	parms2="$parms2 dev $PLUTO_INTERFACE"
+
+	parms3=
+	if [ -n "$PLUTO_MY_SOURCEIP" ]
+	then
+	    if test "$1" = "add"
+	    then
+		addsource6
+                if [	$SOURCEIP_ROUTING_TABLE != "253"      	\
+			-a $SOURCEIP_ROUTING_TABLE != "254"     \
+			-a $SOURCEIP_ROUTING_TABLE != "255" ]
+                then
+                    if ! ip rule list | grep -q "lookup $SOURCEIP_ROUTING_TABLE"
+                    then
+                        ip rule add pref $SOURCEIP_ROUTING_TABLE_PRIO table $SOURCEIP_ROUTING_TABLE
+                     fi
+                fi
+	    fi
+	    parms3="$parms3 src ${PLUTO_MY_SOURCEIP%/*} table $SOURCEIP_ROUTING_TABLE"
+	fi
+
+	case "$PLUTO_PEER_CLIENT_NET/$PLUTO_PEER_CLIENT_MASK" in
+	"::/::")
+		# Vyatta: We do not support this.
+		# opportunistic encryption work around
+		# need to provide route that eclipses default, without
+		# replacing it.
+		# it="ip -6 route $1 ::/1 $parms2 $parms3 &&
+		#	ip route $1 128.0.0.0/1 $parms2 $parms3"
+		# What should       ^^^^ the route be??
+		return $st
+		;;
+	*)	it="ip -6 route $1 $parms1 $parms2 $parms3"
+		;;
+	esac
+	oops="`eval $it 2>&1`"
+	st=$?
+	if test " $oops" = " " -a " $st" != " 0"
+	then
+	    oops="silent error, exit status $st"
+	fi
+	if test " $oops" != " " -o " $st" != " 0"
+	then
+	    echo "$0: doroute6 \`$it' failed ($oops)" >&2
+	fi
+	return $st
+}
+
 
 # in the presence of KLIPS and ipsecN interfaces do not use IPSEC_POLICY
 if [ `echo "$PLUTO_INTERFACE" | grep "ipsec"` ]
@@ -524,11 +619,11 @@ prepare-host-v6:*|prepare-client-v6:*)
 	;;
 route-host-v6:*|route-client-v6:*)
 	# connection to me or my client subnet being routed
-	#uproute_v6
+	uproute_v6
 	;;
 unroute-host-v6:*|unroute-client-v6:*)
 	# connection to me or my client subnet being unrouted
-	#downroute_v6
+	downroute_v6
 	;;
 up-host-v6:)
 	# connection to me coming up
